INSERT INTO product (name, price) VALUES ('Camiseta Hombre', 19.99);
INSERT INTO product (name, price) VALUES ('Pantalón Mujer', 29.99);
INSERT INTO product (name, price) VALUES ('Zapatillas Deporte Hombre', 49.99);
INSERT INTO product (name, price) VALUES ('Chaqueta Mujer', 39.99);
INSERT INTO product (name, price) VALUES ('Sudadera Unisex', 24.99);
INSERT INTO product (name, price) VALUES ('Pantalón De Chándal Hombre', 34.99);
INSERT INTO product (name, price) VALUES ('Zapatillas Casual Mujer', 59.99);
INSERT INTO product (name, price) VALUES ('Camiseta Mujer', 18.99);
INSERT INTO product (name, price) VALUES ('Pantalón De Algodón Hombre', 32.99);
INSERT INTO product (name, price) VALUES ('Botines Mujer', 45.99);
INSERT INTO product (name, price) VALUES ('Camiseta Manga Larga Hombre', 22.50);
INSERT INTO product (name, price) VALUES ('Jersey Mujer', 35.00);
INSERT INTO product (name, price) VALUES ('Zapatillas Running Hombre', 70.00);
INSERT INTO product (name, price) VALUES ('Chaqueta De Cuero Mujer', 89.99);
INSERT INTO product (name, price) VALUES ('Pantalón Skinny Hombre', 27.99);
INSERT INTO product (name, price) VALUES ('Zapatillas Casual Hombre', 55.50);
INSERT INTO product (name, price) VALUES ('Sudadera Capucha Mujer', 28.49);
INSERT INTO product (name, price) VALUES ('Camiseta Estampada Hombre', 21.75);
INSERT INTO product (name, price) VALUES ('Pantalón De Lino Mujer', 41.99);
INSERT INTO product (name, price) VALUES ('Mochila Hombre', 35.50);
INSERT INTO product (name, price) VALUES ('Bolso De Mano Mujer', 49.00);
INSERT INTO product (name, price) VALUES ('Pantalón Deportivo Mujer', 33.20);
INSERT INTO product (name, price) VALUES ('Polo Hombre', 24.00);
INSERT INTO product (name, price) VALUES ('Cazadora Mujer', 50.00);
INSERT INTO product (name, price) VALUES ('Pantalón Jogger Hombre', 36.50);
INSERT INTO product (name, price) VALUES ('Gorra Deportiva Mujer', 15.75);
INSERT INTO product (name, price) VALUES ('Camiseta De Algodón Hombre', 19.50);
